AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sigma-sam-project

  Sample SAM Template for sigma-sam-project

  '
Globals:
  Function:
    Timeout: 3
Resources:
  GetMusicFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lambda-eu-west-1-753745640722/92f5e8831a96149243b78b9ce14e3867
      Handler: handler.music
      Runtime: nodejs14.x
      Architectures:
      - x86_64
      Policies: AmazonDynamoDBFullAccess
      MemorySize: 128
      Events:
        GetMusicApi:
          Type: HttpApi
          Properties:
            Path: /music
            Method: get
        Get1MusicApi:
          Type: HttpApi
          Properties:
            Path: /music/{id}
            Method: get
        PostMusicApi:
          Type: HttpApi
          Properties:
            Path: /music
            Method: post
  DynamoTableFunction:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: dynamodb-music-table
