AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sigma-sam-project

  Sample SAM Template for sigma-sam-project
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetMusicFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: music/
      Handler: handler.music
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies: AmazonDynamoDBFullAccess
      MemorySize: 128
      Events:
        GetMusicApi:
          Type: HttpApi
          Properties:
            Path: /music
            Method: get
        PostMusicApi:
          Type: HttpApi
          Properties:
            Path: /music
            Method: post        
  DynamoTableFunction:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
         Name: id
         Type: String
      TableName: dynamodb-music-table